export const constants = {
  outputFolder: 'mvps_output',
  spritesFolder: 'mvps_icons',
  animatedSpritesFolder: 'mvps_icons_animated',
  mapsFolder: 'maps',
  jsonFile: 'mvpsData.json',
};

export const StatsList = [
  'level',
  'health',
  'str',
  'int',
  'vit',
  'dex',
  'agi',
  'luk',
  'attack',
  'baseExperience',
  'jobExperience',
  'defense',
  'element',
  'race',
  'flee',
  'hit',
  'scale',
  'attackRange',
  'aggroRange',
  'escapeRange',
  'movementSpeed',
  'attackSpeed',
  'attackedSpeed',
  'magicDefense',
];
